services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tienda-prado:
    build: .
    depends_on:
      - db
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    depends_on:
      - db
      - tienda-prado
    ports:
      - 80:80
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  postgres_data:
  caddy-config:
  caddy-data: